spring:
  profiles:
    active: @active-profiles@
  security:
    ignored:
      "/actuator/**,
      /v1/pets/**,
      /v3/api-docs/**,
      /swagger*/**,
      /webjars/**,
      /configuration/**"

server:
  port: 9000

keycloak:
  jwk: ${keycloak.url}/auth/realms/${keycloak.realm}/protocol/openid-connect/certs

logging:
  level:
    org:
      springframework:
        security: INFO
      zalando:
        logbook: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"